[package]
name = "rsterm-config"
version.workspace = true
edition.workspace = true
description = "Shared configuration types for rsTerminal"
license.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
rsterm-uiframe = { workspace = true }
rsterm-connection = { workspace = true }
