[package]
name = "rsterm-fs"
version.workspace = true
edition.workspace = true
description = "Local filesystem and SFTP client for rsTerminal"
license.workspace = true

[dependencies]
directories = "6"
log = "0.4"
russh = "0.60"
russh-sftp = "2.1"
tokio = { version = "1", features = ["full"] }
rsterm-connection = { workspace = true }
